// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: basecampmessageboardmessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BasecampEndpoint.Protobuf {

  /// <summary>Holder for reflection information generated from basecampmessageboardmessage.proto</summary>
  public static partial class BasecampmessageboardmessageReflection {

    #region Descriptor
    /// <summary>File descriptor for basecampmessageboardmessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BasecampmessageboardmessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFiYXNlY2FtcG1lc3NhZ2Vib2FyZG1lc3NhZ2UucHJvdG8SCHR1dG9yaWFs",
            "IvECChtCYXNlY2FtcE1lc3NhZ2VCb2FyZE1lc3NhZ2USQgoHbWVzc2FnZRgB",
            "IAMoCzIxLnR1dG9yaWFsLkJhc2VjYW1wTWVzc2FnZUJvYXJkTWVzc2FnZS5N",
            "ZXNzYWdlRGF0YRJECgpnaXRodWJEYXRhGAIgAygLMjAudHV0b3JpYWwuQmFz",
            "ZWNhbXBNZXNzYWdlQm9hcmRNZXNzYWdlLkdpdGh1YkRhdGESSAoMYmFzZWNh",
            "bXBEYXRhGAMgAygLMjIudHV0b3JpYWwuQmFzZWNhbXBNZXNzYWdlQm9hcmRN",
            "ZXNzYWdlLkJhc2VjYW1wRGF0YRobCgtNZXNzYWdlRGF0YRIMCgR0eXBlGAEg",
            "ASgJGh8KCkdpdGh1YkRhdGESEQoJY29tbWl0U2hhGAEgASgJGkAKDEJhc2Vj",
            "YW1wRGF0YRIdChVtZXNzYWdlQm9hcmRNZXNzYWdlSWQYASABKAkSEQoJcHJv",
            "amVjdElkGAIgASgJQhyqAhlCYXNlY2FtcEVuZHBvaW50LlByb3RvYnVmYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage), global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Parser, new[]{ "Message", "GithubData", "BasecampData" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.MessageData), global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.MessageData.Parser, new[]{ "Type" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.GithubData), global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.GithubData.Parser, new[]{ "CommitSha" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.BasecampData), global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.BasecampData.Parser, new[]{ "MessageBoardMessageId", "ProjectId" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// [START messages]
  /// </summary>
  public sealed partial class BasecampMessageBoardMessage : pb::IMessage<BasecampMessageBoardMessage> {
    private static readonly pb::MessageParser<BasecampMessageBoardMessage> _parser = new pb::MessageParser<BasecampMessageBoardMessage>(() => new BasecampMessageBoardMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BasecampMessageBoardMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BasecampEndpoint.Protobuf.BasecampmessageboardmessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BasecampMessageBoardMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BasecampMessageBoardMessage(BasecampMessageBoardMessage other) : this() {
      message_ = other.message_.Clone();
      githubData_ = other.githubData_.Clone();
      basecampData_ = other.basecampData_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BasecampMessageBoardMessage Clone() {
      return new BasecampMessageBoardMessage(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private static readonly pb::FieldCodec<global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.MessageData> _repeated_message_codec
        = pb::FieldCodec.ForMessage(10, global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.MessageData.Parser);
    private readonly pbc::RepeatedField<global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.MessageData> message_ = new pbc::RepeatedField<global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.MessageData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.MessageData> Message {
      get { return message_; }
    }

    /// <summary>Field number for the "githubData" field.</summary>
    public const int GithubDataFieldNumber = 2;
    private static readonly pb::FieldCodec<global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.GithubData> _repeated_githubData_codec
        = pb::FieldCodec.ForMessage(18, global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.GithubData.Parser);
    private readonly pbc::RepeatedField<global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.GithubData> githubData_ = new pbc::RepeatedField<global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.GithubData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.GithubData> GithubData {
      get { return githubData_; }
    }

    /// <summary>Field number for the "basecampData" field.</summary>
    public const int BasecampDataFieldNumber = 3;
    private static readonly pb::FieldCodec<global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.BasecampData> _repeated_basecampData_codec
        = pb::FieldCodec.ForMessage(26, global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.BasecampData.Parser);
    private readonly pbc::RepeatedField<global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.BasecampData> basecampData_ = new pbc::RepeatedField<global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.BasecampData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Types.BasecampData> BasecampData {
      get { return basecampData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BasecampMessageBoardMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BasecampMessageBoardMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!message_.Equals(other.message_)) return false;
      if(!githubData_.Equals(other.githubData_)) return false;
      if(!basecampData_.Equals(other.basecampData_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= message_.GetHashCode();
      hash ^= githubData_.GetHashCode();
      hash ^= basecampData_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      message_.WriteTo(output, _repeated_message_codec);
      githubData_.WriteTo(output, _repeated_githubData_codec);
      basecampData_.WriteTo(output, _repeated_basecampData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += message_.CalculateSize(_repeated_message_codec);
      size += githubData_.CalculateSize(_repeated_githubData_codec);
      size += basecampData_.CalculateSize(_repeated_basecampData_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BasecampMessageBoardMessage other) {
      if (other == null) {
        return;
      }
      message_.Add(other.message_);
      githubData_.Add(other.githubData_);
      basecampData_.Add(other.basecampData_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            message_.AddEntriesFrom(input, _repeated_message_codec);
            break;
          }
          case 18: {
            githubData_.AddEntriesFrom(input, _repeated_githubData_codec);
            break;
          }
          case 26: {
            basecampData_.AddEntriesFrom(input, _repeated_basecampData_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the BasecampMessageBoardMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class MessageData : pb::IMessage<MessageData> {
        private static readonly pb::MessageParser<MessageData> _parser = new pb::MessageParser<MessageData>(() => new MessageData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<MessageData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MessageData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MessageData(MessageData other) : this() {
          type_ = other.type_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public MessageData Clone() {
          return new MessageData(this);
        }

        /// <summary>Field number for the "type" field.</summary>
        public const int TypeFieldNumber = 1;
        private string type_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Type {
          get { return type_; }
          set {
            type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as MessageData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(MessageData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Type != other.Type) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Type.Length != 0) hash ^= Type.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Type.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Type);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Type.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(MessageData other) {
          if (other == null) {
            return;
          }
          if (other.Type.Length != 0) {
            Type = other.Type;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Type = input.ReadString();
                break;
              }
            }
          }
        }

      }

      public sealed partial class GithubData : pb::IMessage<GithubData> {
        private static readonly pb::MessageParser<GithubData> _parser = new pb::MessageParser<GithubData>(() => new GithubData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<GithubData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public GithubData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public GithubData(GithubData other) : this() {
          commitSha_ = other.commitSha_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public GithubData Clone() {
          return new GithubData(this);
        }

        /// <summary>Field number for the "commitSha" field.</summary>
        public const int CommitShaFieldNumber = 1;
        private string commitSha_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string CommitSha {
          get { return commitSha_; }
          set {
            commitSha_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as GithubData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(GithubData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (CommitSha != other.CommitSha) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (CommitSha.Length != 0) hash ^= CommitSha.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (CommitSha.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(CommitSha);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (CommitSha.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(CommitSha);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(GithubData other) {
          if (other == null) {
            return;
          }
          if (other.CommitSha.Length != 0) {
            CommitSha = other.CommitSha;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                CommitSha = input.ReadString();
                break;
              }
            }
          }
        }

      }

      public sealed partial class BasecampData : pb::IMessage<BasecampData> {
        private static readonly pb::MessageParser<BasecampData> _parser = new pb::MessageParser<BasecampData>(() => new BasecampData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<BasecampData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::BasecampEndpoint.Protobuf.BasecampMessageBoardMessage.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public BasecampData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public BasecampData(BasecampData other) : this() {
          messageBoardMessageId_ = other.messageBoardMessageId_;
          projectId_ = other.projectId_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public BasecampData Clone() {
          return new BasecampData(this);
        }

        /// <summary>Field number for the "messageBoardMessageId" field.</summary>
        public const int MessageBoardMessageIdFieldNumber = 1;
        private string messageBoardMessageId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string MessageBoardMessageId {
          get { return messageBoardMessageId_; }
          set {
            messageBoardMessageId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "projectId" field.</summary>
        public const int ProjectIdFieldNumber = 2;
        private string projectId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string ProjectId {
          get { return projectId_; }
          set {
            projectId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as BasecampData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(BasecampData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (MessageBoardMessageId != other.MessageBoardMessageId) return false;
          if (ProjectId != other.ProjectId) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (MessageBoardMessageId.Length != 0) hash ^= MessageBoardMessageId.GetHashCode();
          if (ProjectId.Length != 0) hash ^= ProjectId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (MessageBoardMessageId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(MessageBoardMessageId);
          }
          if (ProjectId.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(ProjectId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (MessageBoardMessageId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageBoardMessageId);
          }
          if (ProjectId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ProjectId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(BasecampData other) {
          if (other == null) {
            return;
          }
          if (other.MessageBoardMessageId.Length != 0) {
            MessageBoardMessageId = other.MessageBoardMessageId;
          }
          if (other.ProjectId.Length != 0) {
            ProjectId = other.ProjectId;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                MessageBoardMessageId = input.ReadString();
                break;
              }
              case 18: {
                ProjectId = input.ReadString();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
